### ISSUE TITLE
unexpected error when x2 = 0 and n2 = 80,000

### ISSUE THREAD

**Issue by KJByron** [shearer/PropCIs#3]
running a simulation I came across the following unexpected error: 
  PropCIs::diffscoreci(x1 = 4, n1 = 50841, x2 = 0, n2 = 80000, conf.level = 0.95)
  Error in if (score < z) { : missing value where TRUE/FALSE needed
  In addition: Warning message:
  In acos(v/u^3) : NaNs produced

however, the following similar permutations don't give an error:
  PropCIs::diffscoreci(x1 = 0, n1 = 80000, x2 = 4, n2 = 50841, conf.level = 0.95)
  PropCIs::diffscoreci(x1 = 4, n1 = 50841, x2 = 0, n2 = 79999, conf.level = 0.95)
  PropCIs::diffscoreci(x1 = 4, n1 = 50841, x2 = 0, n2 = 80001, conf.level = 0.95)

**Comment by shearer** [comment]
@KJByron Thank you for reporting the issue!
