### ISSUE TITLE
but can you recommend something similar in python ? 

### ISSUE THREAD

**Issue by Sandy4321** [shearer/PropCIs#6]
great package 
but can you recommend something similar in python ?   
especially for  The Clopper–Pearson interval and bounds

**Comment by shearer** [comment]
Sorry for my late reply.
Take a look at statsmodels 
https://github.com/statsmodels/statsmodels

**Comment by Sandy4321** [comment]
I did not find there CI for very small samples
you know it is tricky to do

**Comment by bschneidr** [comment]
This is probably a better question for StackOverflow than for the R package maintainer, so I looked there and found the following resources that directly address your question @Sandy4321:

- https://www.statsmodels.org/devel/generated/statsmodels.stats.proportion.proportion_confint.html
- https://stackoverflow.com/questions/13059011/is-there-any-python-function-library-for-calculate-binomial-confidence-intervals/65873479
- https://stackoverflow.com/questions/51794473/calculating-confidence-interval-for-a-proportion-in-one-sample
